### ISSUE TITLE
Database support

### ISSUE THREAD

**Issue by IJustDev** [j3k0/crm-cli#1]
This project looks really cool. Thank you for sharing this on Github.

This issue may seem like a large enhancement. (Well it is) I would suggest creating a database so the client can change the data on a remote server which is accessible by a team and not only by your own machine.

**Comment by IJustDev** [comment]
you may have a look at [this][repo] repository. It supports client side aswell as server side.

[repo]: https://github.com/pylipp/financeager

**Comment by j3k0** [comment]
So many GitHub notifications that I missed those in this repo.

It would be a nice improvement. I also like having it local, makes it super easy to create reports. The current "database" is a text file that can be kept in sync with git, that's how we do collaboration here, but we're just 2.

**Comment by j3k0** [comment]
Done
