### ISSUE TITLE
Very cool and unique project

### ISSUE THREAD

**Issue by slarrain** [j3k0/crm-cli#5]
I think this is a very cool project. And very unique, by the way. I've been looking for a CRM style thing on the CLI, and haven't been able to find anything. Not even Vimwiki+plugins offer a similar functionality.

Too bad it has become abandoned. It has a lot of potential.

**Comment by j3k0** [comment]
Thanks! At scale it became a little hard to manage and I had other things to do that refactor this. So we migrated CRM to proprietary solution (with built-in integration with Gmail and Stripe...) - not everyone wanted to use mutt 🤓

You inspired me to write my ideas as discussions here:

https://github.com/j3k0/crm-cli/discussions

I do not have any free time at the moment to invest in this unfortunately.
